//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios
    {
        public int IdUsuario { get; set; }
        public string PriNombre { get; set; }
        public string SegNombre { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Usuario { get; set; }
        public byte[] Contraseña { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public string CorreoElectronico { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> FecAlta { get; set; }
        public Nullable<int> PerfilUsuarioId { get; set; }
        public Nullable<int> Intento { get; set; }
        public Nullable<System.DateTime> FecUltimoIntento { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual TblSucursales TblSucursales { get; set; }
        public virtual TblPerfiles TblPerfiles { get; set; }
    }
}
